version: 2.1

orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install pnpm
      - run:
          name: Install dependencies with pnpm (allow lockfile update)
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Run tests
          command: pnpm test
      - run:
          name: Run tests with coverage
          command: pnpm test:cov
      - run:
          name: Upload coverage to Coveralls
          command: ./coveralls report --format lcov --input coverage/lcov.info
      - run:
          name: Build app
          command: pnpm build     
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy:
    jobs:
      - build_and_test