version: 2.1

orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5
  

jobs:
  build_and_test:

    docker:
      - image: cimg/node:20.0.0
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: users_db_test
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install pnpm
      - run:
          name: Install dependencies with pnpm (allow lockfile update)
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Run tests
          command: pnpm test:e2e
      - run:
          name: Run tests with coverage
          command: pnpm test:cov
      - run:
          name: Upload coverage to Coveralls
          command: ./coveralls report --format lcov --input coverage/lcov.info
      - run:
          name: Build app
          command: pnpm build     
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy:
    jobs:
      - build_and_test